### ISSUE TITLE
Oryx doesn't properly consider env variables on Azure DevOps Pipelines

### ISSUE THREAD

**Issue by dan-eversen** [microsoft/Oryx#1019]
For some reason Oryx won't by default consider env variables injecting into the build process by Azure DevOps Pipelines. For example, the following pipeline won't work as intended if trying to create and deploy a static react app with the env variable `REACT_APP_MAP_API_KEY` (which is then accessible in the app via `process.env.REACT_APP_MAP_API_KEY`:

```
trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
- group: api-key-group

steps:
  - task: CmdLine@2
    inputs:
      script: 'echo $(REACT_APP_MAP_API_KEY)'
  - checkout: self
    submodules: true
  - task: AzureStaticWebApp@0
    inputs:
      app_location: '/'
      api_location: 'api'
      output_location: ''
    env:
      azure_static_web_apps_api_token: $(deployment_token)
      REACT_APP_MAP_API_KEY: $(REACT_APP_MAP_API_KEY)
```

However, the following code WILL work as intended:

```
trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
- group: api-key-group

steps:
  - checkout: self
    displayName: Checkout code
  
  - task: Bash@3
    displayName: Build
    inputs:
      targetType: 'inline'
      script: |        
        npm install 
        npm run build
    env:
      REACT_APP_MAP_API_KEY: $(REACT_APP_MAP_API_KEY)

  - task: AzureStaticWebApp@0
    displayName: Deploy
    inputs:
      app_location: '/'
      app_build_command: 'echo 1'
      output_location: 'build'
    env:
      azure_static_web_apps_api_token: $(deployment_token)
```

I was able to log the Pipeline injection of the API key, so I can confirm that it's being loaded into the env. Looking at the source code, it seems like Oryx is simply failing to consider the env variables, causing the default Azure pipeline example to break, and making it much more difficult to figure out how to get this to work (find that workaround was actually quite difficult - it was fairly obscure).

Proposed fix: Oryx detects the variables injected by Pipeline properly and uses them in the build process.
