### ISSUE TITLE
[Feature] pnpm support

### ISSUE THREAD

**Issue by lwyj123** [microsoft/Oryx#1150]
### Feature Request
I found the [nodejs build document](https://github.com/microsoft/Oryx/blob/main/doc/runtimes/nodejs.md) but didn't find pnpm support. now I use `PRE_BUILD_COMMAND` and `CUSTOM_BUILD_COMMAND` for this but it's good that Oryx could have official support like `yarn` and `lerna`

**Comment by jechtom** [comment]
As @lwyj123 wrote you can workaround this with extending github action step `Azure/static-web-apps-deploy@v1` yaml with env variables:
```yaml
        env:
          PRE_BUILD_COMMAND: npm install -g pnpm
          CUSTOM_BUILD_COMMAND: pnpm install && pnpm run build
```
