### ISSUE TITLE
Failure during content distribution

### ISSUE THREAD

**Issue by laurekamalandua** [microsoft/Oryx#1613]
**Description**

When deploying an Azure Static Web App from Azure DevOps using the AzureStaticWebApp@0 task, deployment fails. Oryx builds the project and uploads the content. After 1:30, polling returns that Azure labeled the deployment as failed. The issue does not occur when only static content is uploaded. The binaries do not exceed 500 MB.

**Reproduction**

1. Use Azure DevOps task: AzureStaticWebApp@0 with the following specification: 

```
 - task: AzureStaticWebApp@0
            displayName: "Static Web App: $(name)"
            inputs:
              workingDirectory: $(Pipeline.Workspace)
              app_location: "/app"
              api_location: "/app/api/"
              config_file_location: "/app"
              skip_app_build: true
              skip_api_build: false
              is_static_export: false
              verbose: true
              azure_static_web_apps_api_token: "$(token)"
              deployment_environment: Development
              production_branch: main
``` 

**Expected behavior**

Return comprehensive error logging on Oryx end to understand the deployment failure. Azure back-end should provide more information and this should be available for end-users.

**Screenshots**

<img width="786" alt="Screenshot 2022-10-16 at 02 39 43" src="https://user-images.githubusercontent.com/12623827/196012611-271d5d5d-4a88-4c59-8843-378c1b5817d4.png">

**Device info (if applicable):**
 - OS: ubuntu (Microsoft hosted agent)
 - Browser: NA
 - Version: NA

**Additional context**

Application with Azure Functions back-end (default HTTP binding). The configuration file is as follows: 

```
{
  "routes": [
    {
      "route": "/*",
      "methods": [
        "GET",
        "POST"
      ]
    }
  ],
  "platform": {
    "apiRuntime": "node:16"
  }
}
```

The following aspects apply: 
- we make no use of the Github Actions workflow. 
- we checked whether any directory paths contained non ASCII characters. This is not the case.
