### ISSUE TITLE
error NU1101: Unable to find package

### ISSUE THREAD

**Issue by jkears** [microsoft/Oryx#1614]
We are deploying to Azure Static Web apps and our Blazor WASM (SPA) has package references to our private nuget service. 
When we run the generated GitHub Action (via Azure Static Web Apps),.  we get a bunch of errors saying, not able to resolve packages within our private nuget service.  

We have included Nuget.Config files in both the root of the solution as well as the WASM project. 

We further tried to influence the build processor, with the following to include the following step (see next), pre-build but it does not seem to influence the Oryx build process.

```
 - name: Add Private Nextware Nuget source
        run: dotnet nuget add source https://nwnuget.azurewebsites.net/nuget --name nwnuget

```

Here is our full GitHub Build/Deploy Action ...

```
name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Add Private Nextware Nuget source
        run: dotnet nuget add source https://nwnuget.azurewebsites.net/nuget --name nwnuget
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_JOLLY_SKY_0E29A4D0F }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "NextWare.Portal.Wasm" # App source code path
          api_location: "" # Api source code path - optional
          output_location: "wwwroot" # Built app content directory - optional
          ###### End of Repository/Build Configurations ######

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_JOLLY_SKY_0E29A4D0F }}
          action: "close"
```

How to include our private nuget reference?

**Comment by jkears** [comment]
Using [this information](https://www.meziantou.net/using-a-custom-build-pipeline-with-azure-static-web-apps.htm), I changed the WF to build the project manually, outside of Oryx...


```
name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      # build the app manually
      - name: Add Private Nextware Nuget source 
        run: dotnet nuget add source https://nwnuget.azurewebsites.net/nuget --name nwnuget 
      - name: run manual build
        run: dotnet publish --output dist
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_JOLLY_SKY_0E29A4D0F }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "dist/wwwroot"
          api_location: "" # Api source code path - optional
          skip_app_build: true
          skip_api_build: true
          ###### End of Repository/Build Configurations ######

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_JOLLY_SKY_0E29A4D0F }}
          action: "close"

```
