### ISSUE TITLE
Custom install for react-scripts npm

### ISSUE THREAD

**Issue by 8bg** [microsoft/Oryx#1714]
This is not necessarily a bug, but I've been searching for hours and can't seem to find how to inject custom npm install flags. For this project, we need to run 

npm install --react-scripts

I don't see a way to do this using the Oryx env variables list https://github.com/microsoft/Oryx/blob/main/doc/configuration.md 

Is there some other env variable I can put in the yml deploy file to accomplish this?

thank you

**Comment by pauld-msft** [comment]
Hi @8bg, you can use the CUSTOM_BUILD_COMMAND env var to control the installation script as well. Just keep in mind that if you do, you will also need to run the build command, e.g.
```
CUSTOM_BUILD_COMMAND: 'npm install --react-scripts && npm run build'
```

**Comment by 8bg** [comment]
Ah, that is great @pauld-msft -- MANY thanks for your quick response!

**Comment by bh3605** [comment]
> Hi @8bg, you can use the CUSTOM_BUILD_COMMAND env var to control the installation script as well. Just keep in mind that if you do, you will also need to run the build command, e.g.
> 
> ```
> CUSTOM_BUILD_COMMAND: 'npm install --react-scripts && npm run build'
> ```

How do you specify this in a YAML pipeline? Take this job for example below. What needs added so I can call a custom npm script specified in package.json?

```
job: 
  displayName: Build Application
  container: 'mcr.microsoft.com/oryx/build:latest'
  steps:
    - checkout: self
    - task: DownloadSecureFile@1
      name: npmrc
      inputs:
        secureFile: 'private.npmrc'
    - script: |
        mv $(npmrc.secureFilePath) .npmrc
      displayName: 'Move secure file'
    - script: oryx build $(Build.SourcesDirectory) --output $(Build.ArtifactStagingDirectory)
    - ${{if eq(parameters.isSWA, true)}}:
      - script: cp $(Build.SourcesDirectory)/staticwebapp.config.json $(Build.ArtifactStagingDirectory)/dist/${{parameters.outputDir}}
    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(Build.ArtifactStagingDirectory)/dist'
        artifact: 'drop'
        publishLocation: 'pipeline'
```
