### ISSUE TITLE
YAML step to include custom folder or file inside output_location for Static Web Apps

### ISSUE THREAD

**Issue by borisimple** [microsoft/Oryx#1720]
### Feature Request

I don't see a way to include ads.txt file which is provided by Google AdSense in the root directory for my app.

I am using Hugo application and it would be nice if we could specify that specific file or folder which should be included in our build (last line in the example under).

```
jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_WITTY_POND_05DC08703 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} 
          action: "upload"
          app_location: "/"
          api_location: ""
          output_location: "public"
          include: [".custom-file.txt", "./custom-folder"]
```

Well, it seems that we can always copy files (or create desired folders) in the Static directory. Then those files will be available in the root of a build.
