### ISSUE TITLE
Bitbucket pipe demo stalled on npm install

### ISSUE THREAD

**Issue by williamcspace** [microsoft/Oryx#1937]
Hi,

I follow this documentation to run pipeline task in bitbucket for react.js, but the task is stalled with `npm install` line for two hours.

https://learn.microsoft.com/en-us/azure/static-web-apps/bitbucket?tabs=react

is there anyone encountered this issues?

appreciate your helps.

`
Starting to build app with Oryx
Azure Static Web Apps utilizes Oryx to build both static applications and Azure Functions. You can find more details on Oryx here: https://github.com/microsoft/Oryx
Calling oryx build "/opt/atlassian/pipelines/agent/build" -o /bin/staticsites/25c5f6f7-9505-45c7-9228-885a2081a47a-swa-oryx/app --manifest-dir /bin/staticsites/25c5f6f7-9505-45c7-9228-885a2081a47a-swa-oryx/app-manifest -p require_build -p disable_recursive_lookup=true -p ORYX_APP_TYPE="static-sites" -p NODE_DEFAULT_VERSION=16 -p DOTNET_DEFAULT_VERSION=6 -p PYTHON_DEFAULT_VERSION=3.9
---Oryx build logs---

Operation performed by Microsoft Oryx, https://github.com/Microsoft/Oryx
You can report issues at https://github.com/Microsoft/Oryx/issues

Oryx Version: 0.2.20221103.1, Commit: a2c65dde152b749fea395f4d1242ea9350942258, ReleaseTagName: 20221103.1

Build Operation ID: |PAAapjHKuog=.1bce658a_
Repository Commit : ae8af24b069d8b52b191eeb6b9e53c37f31c406e

Detecting platforms...
Detected following platforms:
  nodejs: 16.19.0
Version '16.19.0' of platform 'nodejs' is not installed. Generating script to install it...
Detected the following frameworks: React

Source directory     : /opt/atlassian/pipelines/agent/build
Destination directory: /bin/staticsites/25c5f6f7-9505-45c7-9228-885a2081a47a-swa-oryx/app

Downloading and extracting 'nodejs' version '16.19.0' to '/opt/nodejs/16.19.0'...
Detected image debian flavor: bullseye.
Downloaded in 0 sec(s).
Verifying checksum...
Extracting contents...
performing sha512 checksum for: nodejs...
Done in 1 sec(s).

Removing existing manifest file
Creating directory for command manifest file if it does not exist
Creating a manifest file...
Node Build Command Manifest file created.

Using Node version:
v16.19.0
Using Npm version:
8.19.3

Running 'npm install --unsafe-perm'...
`

**Comment by snehapar9** [comment]
Thanks for submitting this issue @williamcspace! Do you mind sharing your pipeline's yaml?

**Comment by williamcspace** [comment]
Sure.

Initially I use the same code from above documentation with create-react-app template project.
```
pipelines:
  branches:
   main:
    - step: 
        name: Deploy to test
        deployment: test
        script:
          - pipe: microsoft/azure-static-web-apps-deploy:main
            variables:
                APP_LOCATION: '$BITBUCKET_CLONE_DIR'
                OUTPUT_LOCATION: '$BITBUCKET_CLONE_DIR/build'
                API_TOKEN: $deployment_token
```

and then I increased the docker memory to 3072 for production project (with more npm dependencies), still stuck in Oryx npm install stage.
```
definitions:
  services:
    docker:
      memory: 3072
      
options:
  max-time: 15

pipelines:
  branches:
    master:
      - step:
          name: 'Deploy to Production'
          deployment: 'Production'
          script:
            - pipe: 'microsoft/azure-static-web-apps-deploy:main'
              variables:
                APP_LOCATION: '$BITBUCKET_CLONE_DIR'
                OUTPUT_LOCATION: '$BITBUCKET_CLONE_DIR/build'
                API_TOKEN: $deployment_token
```

**Comment by snehapar9** [comment]
Thanks! Could you also please let me know if you're using the repo in the document or a different repo? If you're using a different repo, is the link available to share? May not be related to why npm install is stalling but would be helpful if you could share the value for `BITBUCKET_CLONE_DIR` so we can try reproducing the problem.

**Comment by williamcspace** [comment]
I was using exactly the same setup as documentation, basically

1. npx create-react-app demo

2. copy pipelines.yml from documentation and run pipeline.

**Comment by snehapar9** [comment]
Thanks @williamcspace! I was able to reproduce the issue with the first pipeline you shared previously. It seems like npm install was stalling because `Container 'docker' exceeded memory limit` in bitbucket. 

However, I was able to successfully deploy with the second pipeline you shared. Do you mind re-running the second pipeline?
If that doesn't work, you could add `size: 2x` to your deployment step to increase the memory limit. Would that work for you?

```
definitions:
  services:
    docker:
      memory: 3072
      
options:
  max-time: 15

pipelines:
  branches:
    master:
      - step:
          name: 'Deploy to Production'
          deployment: 'Production'
          script:
            - pipe: 'microsoft/azure-static-web-apps-deploy:main'
              variables:
                APP_LOCATION: '$BITBUCKET_CLONE_DIR'
                OUTPUT_LOCATION: '$BITBUCKET_CLONE_DIR/build'
                API_TOKEN: $deployment_token
```
