### ISSUE TITLE
Oryx unable to detect .net solution

### ISSUE THREAD

**Issue by bh3605** [microsoft/Oryx#2001]
### Bug Report

- What happened?
I'd expect oryx to be able to detect a .net solution and build the solution.

- Do you have log output? Please include between the backticks:

I made sure the directory it was targeting was populated. Hence the first screenshot of me checking the code is where it should be.
![image](https://github.com/microsoft/Oryx/assets/3073436/1e0c9e73-9d16-40f4-926b-ee2e03818eb9)
![image](https://github.com/microsoft/Oryx/assets/3073436/202a7846-37f1-4483-96b1-6c504497bf75)

**Comment by johnholliday** [comment]
Getting the same issue.  Thought it might be related to node version upgrade to 16 for GitHub actions, but seems to be a problem with Oryx unable to detect the language.

**Comment by bh3605** [comment]
I would've thought this would've been low hanging fruit for them to reply to...

**Comment by daniv-msft** [comment]
Thanks for reporting this issue. @waliMSFT, could you please have a look into it?
@bh3605 Just to have all the context, did you run Oryx directly? If not, could you please share the product where this originated (App Service, Static Web Apps, etc.)?

**Comment by bh3605** [comment]
I am aware my last two steps aren't going to work, but I'm just messing around with getting Oryx working first.

Azure Devops. Here's my yaml:
```
trigger:
    branches:
        include:
        - master
    paths:
        exclude:
        - azure-pipelines.yml

pool:
    vmImage: ubuntu-latest

jobs:
- job: 
  displayName: Build Application
  container: 'mcr.microsoft.com/oryx/build:latest'
  steps:
    - checkout: self
    - script: echo $(Build.SourcesDirectory)
    - script: cd $(Build.SourcesDirectory) & ls
    - script: oryx build $(Build.SourcesDirectory) --output $(Build.ArtifactStagingDirectory)
    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(Build.ArtifactStagingDirectory)/dist'
        artifact: 'drop'
        publishLocation: 'pipeline'
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'
        StoreAsTar: true
```
