### ISSUE TITLE
Error: Platform 'golang' version '1.21.6' is unsupported

### ISSUE THREAD

**Issue by mrThirsty** [microsoft/Oryx#2396]
### Bug Report

I created a new Static Web site in Azure, and linked it to my Azure DevOps repo to automatically build and publish. The pipeline, which is included below, was created and run, and it errored with "Error: Platform 'golang' version '1.21.6' is unsupported".

I have a Hugo static website setup, it builds and runs fine when using a local Hugo server on my machine.

- At what date and time did you most recently experience the problem?
20/03/2024 10:16 UTC.

- Where did you experience the problem? E.g. Azure Web Apps, Azure Functions, Azure Container Registry, or offline use.
Azure Static Web site

- If your repo is publicly available please share its URL:
It is not.

- What happened?
Azure Static Website created the pipeline in my repo and ran it and it failed.

- What did you expect or want to happen?
To deploy the code base in the Repo to the newly created Azure Static website.

- How can we reproduce it?
Create a basic Hugo website, steps available here: https://gohugo.io/getting-started/quick-start/ and push the working code to an Azure DevOps repo.
Create a new Azure Static website in the Azure Portal, and select Azure DevOps as your deployment source and point it to the repo with the above code.
Create the Static website and let the pipeline run.

- Do you have log output? Please include between the backticks:
Yes, have attached it to this bug report.

Below is the pipeline created by Azure when setting up the Azure Static Website:
```
name: Azure Static Web Apps CI/CD

pr:
  branches:
    include:
      - main
trigger:
  branches:
    include:
      - main

jobs:
- job: build_and_deploy_job
  displayName: Build and Deploy Job
  condition: or(eq(variables['Build.Reason'], 'Manual'),or(eq(variables['Build.Reason'], 'PullRequest'),eq(variables['Build.Reason'], 'IndividualCI')))
  pool:
    vmImage: ubuntu-latest
  variables:
  - group: Azure-Static-Web-Apps-zealous-flower-0edcb1403-variable-group
  steps:
  - checkout: self
    submodules: true
  - task: AzureStaticWebApp@0
    inputs:
      azure_static_web_apps_api_token: $(AZURE_STATIC_WEB_APPS_API_TOKEN_ZEALOUS_FLOWER_0EDCB1403)
###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
# For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
      app_location: "/" # App source code path
      api_location: "" # Api source code path - optional
      output_location: "public" # Built app content directory - optional
###### End of Repository/Build Configurations ######
```

[AzureStaticWebApp_Log.txt](https://github.com/microsoft/Oryx/files/14664881/AzureStaticWebApp_Log.txt)
