### ISSUE TITLE
Hugo build twice

### ISSUE THREAD

**Issue by kozw** [microsoft/Oryx#615]
Following the instructions on [publishing a Hugo site to Azure Static Web Apps](https://docs.microsoft.com/en-us/azure/static-web-apps/publish-hugo), it seems the Hugo build step is executed twice. Once in Build and once in Build and Deploy. By itself that is not necessarily a major issue, however the Build and Deploy step performed by Oryx uses Hugo v0.59.1 while I require at least Hugo 0.62, and preferably the latest (0.71)

Two questions:
- Can Oryx be configured to use the latest Hugo version?
- Why is Hugo build twice (in Build and in Build And Deploy)

Build log:
[1_Build and Deploy Job.txt](https://github.com/microsoft/Oryx/files/4674136/1_Build.and.Deploy.Job.txt)

**Comment by wictorwilen** [comment]
This is a major issue and very confusing. Hugo 0.59 is very old and I would like to see either in option in the SWA deploy action to specify Hugo version or use Hugo 0.71/latest.

**Comment by BorisWilhelms** [comment]
Not only latest should be an option, but also the extended version of hugo!

**Comment by BorisWilhelms** [comment]
I have researched more, and if you follow the documentation, hugo build is NOT run twice. The custom steps will build hugo and output to /public. The step Azure/static-web-apps-deploy@v0.0.1-preview will then pickup the files from /public and assume that they are already build. You should get the message

`Oryx was unable to determine the build steps. Continuing assuming the assets in this folder are already built. If this is an unexpected behavior please contact support.`

Please check if `app_location` and `app_artifact_location` are set correctly.

Example:
```yaml
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2.4.8
      with:
        hugo-version: "latest"
        extended: true

    - name: Build
      run: hugo -s ./src -d ../public
    
    - name: Build And Deploy
      id: builddeploy
      uses: Azure/static-web-apps-deploy@v0.0.1-preview
      with:
        azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_GRAY_SEA_084F1EB03 }}
        repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
        action: 'upload'
        ###### Repository/Build Configurations - These values can be configured to match you app requirements. ######
        # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig 
        app_location: 'public' # App source code path
        api_location: 'api' # Api source code path - optional
        app_artifact_location: '' # Built app content directory - optional
        ###### End of Repository/Build Configurations ######
```
With the custom step we can use whatever version of hugo we like. Including extended versions.
