### ISSUE TITLE
Javascript app - install private repositories

### ISSUE THREAD

**Issue by yvandeghellinck** [microsoft/Oryx#636]
### Feature Request

There is a way to install some private repository from npm? I try to add ```.npmrc``` with read only credential. But script failed while downloading my private repository. Can we override the ```npm install``` script? Or any other way?

Many thanks!

**Comment by kichalla** [comment]
Hi @yvandeghellinck Could you please share what errors did you see when you tried this out? Was it related to authentication/authorization of your private repository?

**Comment by kichalla** [comment]
Here is an example on how you could do...I have a private npm registry hosted in GitHub and this is how I have in my npm registry:
Here the ${GITHUB_TOKEN} is expanded by npm when ‘npm install’ is called. You just need to make sure this variable's value is available as an environment variable.

```
registry=https://registry.npmjs.org/
@kichalla:registry=https://npm.pkg.github.com/
//npm.pkg.github.com/:_authToken=${GITHUB_TOKEN}
```

**Comment by getfatday** [comment]
@kichalla I can confirm this approach is not working in my case. Also following this issue in Azure/static-web-apps#44, since they appear to be the same.

Here is my `.npmrc`:

``` sh
registry=https://registry.npmjs.org/
//registry.npmjs.org/:_authToken=${NPM_TOKEN}
```

And my Github Action configuration:

``` yaml
      ...
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v0.0.1-preview
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_***** }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match you app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "/packages/app" # App source code path
          api_location: "." # Api source code path - optional
          app_artifact_location: "dist" # Built app content directory - optional
          ###### End of Repository/Build Configurations ######
   ...
```

I'm not understanding how Oryx would pickup on this environment variable, since it's not being passed into Docker. Here is the command as posted in the Github Action log.

``` sh
/usr/bin/docker run --name d3506d5a575c38448f97be11ee182dfe42_a28e0e --label 3888d3 --workdir /github/workspace --rm -e NPM_TOKEN -e INPUT_AZURE_STATIC_WEB_APPS_API_TOKEN -e INPUT_REPO_TOKEN -e INPUT_ACTION -e INPUT_APP_LOCATION -e INPUT_API_LOCATION -e INPUT_APP_ARTIFACT_LOCATION -e INPUT_API_BUILD_COMMAND -e INPUT_APP_BUILD_COMMAND -e INPUT_ROUTES_LOCATION -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/*****":"/github/workspace" 3888d3:506d5a575c38448f97be11ee182dfe42
```

I also attempted to hard code the NPM auth token in the `.npmrc` file, but it didn't seem to help.

Here is the NPM output from the Github Action log:
``` sh
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@****** - Not found
npm ERR! 404 
npm ERR! 404  '@******@^2.2.0' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of '__oryx_prod_node_modules'
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
```

I should also note, that this works fine locally. I should also note that we use `yarn` and the repo contains a `yarn.lock` file, but Oryx still chooses `npm`.

At this point, I'm prepared to abandon Oryx, but it seems to be the only method to deploy a static web app as advertised. If you have any alternatives, I prepared to explore those options as well.

**Comment by mahmoudajawad** [comment]
Yup. This and #44 are the same. I would suggest closing and following one of them to track this issue until it's resolved.

**Comment by kichalla** [comment]
@getfatday Thanks for the details. Could you share the following details?

- If possible could you share a repro project or a picture of root directory structure of your project?
- You were saying that `npm` is being used even though `yarn.lock` exists. This should not be happening. Could you share the repro? I just now tried a sample app with package.json, yarn.lock and I see yarn being used.
- Oryx does not do anything regarding the `NPM_TOKEN` used in your example. Npm expands the token used in the .npmrc file. You were mentioning that it works on your machine. Did you use npm to restore or yarn to restore? Yarn seems to have a different format for the .npmrc equivalent file?

**Comment by kichalla** [comment]
Adding to my earlier questions: Could you please share the build output of your workflow run?
Interesting article about .yarnrc: https://joegornick.com/2019/04/15/yarn-with-private-npm-registries-and-authentication/

**Comment by getfatday** [comment]
@kichalla thanks for the follow up. Here is the directory structure, with most of the source code files removed:

``` sh
.gitattributes
.github/workflows/azure-static-web-apps-******.yml
.gitignore
.npmrc
lerna.json
package.json
packages/app/.env
packages/app/README.md
packages/app/lib/index.tsx
packages/app/package.json
packages/app/tsconfig.json
yarn.lock
```

Keep in mind that this repo uses a [Yarn workspace](https://classic.yarnpkg.com/en/docs/workspaces/) to support multiple packages.

Also, the article you mentioned is in regard to alternative NPM registries (private or public). The issue here is accessing private packages hosted in NPM proper at `https://registry.npmjs.org/`, that require an authentication token to access them. In other systems, writing a `.npmrc` file at build time has been sufficient for Yarn to pickup the authentication token. 

Here is an example from our CircleCI build which simple writes the token to `.npmrc`, yet installs packages with Yarn.

``` yaml
  npm-config:
    description: "Initialize NPM"
    parameters:
      npm-auth-token:
        type: env_var_name
        default: NPM_TOKEN
        description: "NPM Auth Token"
    steps:
      - run:
          name: npm config
          command: |
            echo "//registry.npmjs.org/:_authToken=${<< parameters.npm-auth-token >>}" > ~/.npmrc
``` 

In your tests, are you trying to access a private NPM package?

**Comment by getfatday** [comment]
@kichalla I also wanted to mention that I did attempt a build by hard coding the NPM auth token directly into the stored `.npmrc` file. This, unfortunately, did not work either, but it does show that, regardless of variable expansion in `.npmrc` file, that authentication with an `.npmrc` isn't working as expected.

**Comment by kichalla** [comment]
Thanks for the quick response @getfatday Will get back to you. I have only tested with private repository on GitHub and do not have a private repository on NPM itself.

**Comment by kichalla** [comment]
BTW could you please share the build output (removing any irrelevant/privacy related parts). I want to confirm if yarn or npm is being used to build your app. I would expect yarn to be used since we give preference to Yarn if we find yarn.lock file.

**Comment by getfatday** [comment]
Thanks @kichalla here's the output:

``` sh
##[group]Run Azure/static-web-apps-deploy@v0.0.1-preview
with:
  azure_static_web_apps_api_token: ***
  repo_token: ***
  action: upload
  app_location: /packages/app
  api_location: .
  app_artifact_location: dist
env:
  NPM_TOKEN: ***
##[endgroup]
RE_STATIC_WEB_APPS_API_TOKEN -e INPUT_REPO_TOKEN -e INPUT_ACTION -e INPUT_APP_LOCATION -e INPUT_API_LOCATION -e INPUT_APP_ARTIFACT_LOCATION -e INPUT_API_BUILD_COMMAND -e INPUT_APP_BUILD_COMMAND -e INPUT_ROUTES_LOCATION -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/******":"/github/workspace" 3888d3:b39b67e9c0fb42eab01095e9a504f78d
DeploymentId: b03acca8-4a17-4b15-b470-9a089c22a57b

App Directory Location: '/packages/app' was found.
Api Directory Location: '.' was found.
Starting to build app with Oryx
Azure Static Web Apps utilizes Oryx to build both static applications and Azure Functions. You can find more details on Oryx here: https://github.com/microsoft/Oryx
---Oryx build logs---


Build orchestrated by Microsoft Oryx, https://github.com/Microsoft/Oryx
You can report issues at https://github.com/Microsoft/Oryx/issues

Oryx Version      : 0.2.20200526.1, Commit: 400c4f0c491327b894c3bed2cfbe68376e17eabd, ReleaseTagName: 20200526.1
Build Operation ID: |b89M4/bdfL8=.825787ce_
Repository Commit : e6b64d3333b0d3a7810506fbecc177868b8874ca

Using intermediate directory '/bin/staticsites/ss-oryx/app-int'.

Intermediate directory doesn't exist, creating it...'

Copying files to the intermediate directory...
Done in 0 sec(s).

Source directory     : /bin/staticsites/ss-oryx/app-int
Destination directory: /bin/staticsites/ss-oryx/app


Using Node version:
v12.16.3

Using Npm version:
6.14.4

Installing production dependencies in '/bin/staticsites/ss-oryx/app-int/__oryx_prod_node_modules'...

Running 'npm install --unsafe-perm --production'...

npm WARN deprecated core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
npm WARN deprecated chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@****** - Not found
npm ERR! 404
npm ERR! 404  '@******@^2.2.0' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of '__oryx_prod_node_modules'
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
debug.log


---End of Oryx build logs---
Oryx has failed to build the solution.
Exiting
```

And if needed, here is the root `package.json` file:

``` json
{
  "name": "@******",
  "version": "0.0.0",
  "description": "******",
  "private": true,
  "workspaces": [
    "packages/*"
  ],
  "scripts": {
    "start": "lerna run start --stream",
    "build": "lerna run build --stream",
    "clean": "lerna clean",
    "deploy": "lerna run deploy --stream"
  },
  "license": "MIT",
  "devDependencies": {
    "lerna": "^3.22.1",
    "serverless": "^1.73.1",
    "tslib": "^2.0.0",
    "typescript": "^3.9.5"
  }
}
```

**Comment by getfatday** [comment]
@kichalla some progress made regarding the Yarn detection and `.npmrc`, it looks like setting `app_location` determines where Oryx runs its commands.

My original configuration was:

``` yaml
app_location: "packages/app" # App source code path
app_artifact_location: "dist" # Built app content directory - optional
```

Making the following adjustment works

``` diff
-app_location: "packages/app" # App source code path
+app_location: "." # App source code path
-app_artifact_location: "dist" # Built app content directory - optional
+app_artifact_location: "packages/app/dist" # Built app content directory - optional
```

This makes sense if Oryx was running from `packages/app`, since that directory doesn't contain a `yarn.lock` (Yarn detection) or `.npmrc` authentication.

I still think there is some sort of issue here, either:
- Update the documentation to let the user know that `app_location` determines where commands are run
- Provide a another input like `project_location` to determine where commands are run
- Update Oryx to consider that the project root, in the case of a monorepo may not be in the `app_location`, so search up the parent directory structure to find the `yarn.lock` or `package-lock.json`

**Comment by getfatday** [comment]
@kichalla one last post to follow up. I was able to verify a successful deployment with the following Github Action configuration which includes creating the `.npmrc` at build time.

``` yaml
jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
        # Creates an .npmrc using an NPM token stored as a Github secret
      - name: NPM Token
        run: 'echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc'
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v0.0.1-preview
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_****** }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          # App location determines where Oryx runs its install and build commands
          app_location: "/"
          api_location: "api"
          # Actual App artifacts are stored in a Yarn workspace package's distribution directory
          app_artifact_location: "packages/app/dist"
```

**Comment by kichalla** [comment]
Awesome, thanks @getfatday. I took a note of the suggestions you provided in the earlier post. We will try to make the experience better. 

@mahmoudajawad Could you also check your workflow again?

**Comment by mahmoudajawad** [comment]
Unfortunately, @kichalla, it's not working for me. I updated the workflow to:
```yaml
name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
    - master
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
    - master

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
    - uses: actions/checkout@v2
    - name: NPM Token
      run: |
        echo "@ORG_NAME:registry=https://npm.pkg.github.com/ORG_NAME
        //npm.pkg.github.com/:_authToken=$NPM_TOKEN
        always-auth=true" > .npmrc
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    - name: Confirm NPM Token
      run: cat .npmrc
    - name: Build And Deploy
      id: builddeploy
      uses: Azure/static-web-apps-deploy@v0.0.1-preview
      with:
        azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_HAPPY_SAND_03B480303 }}
        repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
        action: 'upload'
        ###### Repository/Build Configurations - These values can be configured to match you app requirements. ######
        # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig 
        app_location: '/' # App source code path
        app_build_command: 'ng build --prod'
        app_artifact_location: 'dist/madf-boilerplate' # Built app content directory - optional
        ###### End of Repository/Build Configurations ######

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
    - name: Close Pull Request
      id: closepullrequest
      uses: Azure/static-web-apps-deploy@v0.0.1-preview
      with:
        azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_HAPPY_SAND_03B480303 }}
        action: 'close'

```

I added `Confirm NPM Token` step in order to confirm whether the file is created or not, and can confirm it's being created correctly. However, for some reason, it's still not being used to access the package.

**Comment by mahmoudajawad** [comment]
Unfortunately, @kichalla, it's not working for me. I updated the workflow to:
```yaml
name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
    - master
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
    - master

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
    - uses: actions/checkout@v2
    - name: NPM Token
      run: |
        echo "@ORG_NAME:registry=https://npm.pkg.github.com/ORG_NAME
        //npm.pkg.github.com/:_authToken=$NPM_TOKEN
        always-auth=true" > .npmrc
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    - name: Confirm NPM Token
      run: cat .npmrc
    - name: Build And Deploy
      id: builddeploy
      uses: Azure/static-web-apps-deploy@v0.0.1-preview
      with:
        azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_******* }}
        repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
        action: 'upload'
        ###### Repository/Build Configurations - These values can be configured to match you app requirements. ######
        # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig 
        app_location: '/' # App source code path
        app_build_command: 'ng build --prod'
        app_artifact_location: 'dist/madf-boilerplate' # Built app content directory - optional
        ###### End of Repository/Build Configurations ######

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
    - name: Close Pull Request
      id: closepullrequest
      uses: Azure/static-web-apps-deploy@v0.0.1-preview
      with:
        azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_***** }}
        action: 'close'

```

I added `Confirm NPM Token` step in order to confirm whether the file is created or not, and can confirm it's being created correctly. However, for some reason, it's still not being used to access the package.

**Comment by mahmoudajawad** [comment]
@kichalla, I noticed this in the logs:
```yaml
Using intermediate directory '/bin/staticsites/ss-oryx/app-int'.

Intermediate directory doesn't exist, creating it...'

Copying files to the intermediate directory...
Done in 0 sec(s).

Source directory     : /bin/staticsites/ss-oryx/app-int
Destination directory: /bin/staticsites/ss-oryx/app
```
 Since, the talk here is about file not being copied when the app is being built, could these previous lines from `Oryx` step could mean it again is copying the files leaving behind `.npmrc` file?

**Comment by kichalla** [comment]
Thanks for the details @mahmoudajawad...is the package dependency that you are having problem with is part of "dependencies" or "devDependencies"? if it is part of "dependencies", could you try and see if you are hitting the same issue when you move it to "devDependencies"? Could you please confirm? If this works, it can be used as a temporary workaround. We will get out a fix to make this work meanwhile.

**Comment by mahmoudajawad** [comment]
@kichalla, I can confirm moving the package from `dependencies` to `devDependencies` fixes the problem and it successfully gets Oryx to build the app, other parts concerning SWA are also working and the app has been successfully deployed. 

Great tip and I can live with this as long as it's stated as well-known issue with the resolution suggested here.

**Comment by kichalla** [comment]
Thanks you very much! @mahmoudajawad From Oryx's side we will be getting out a fix asap and will update this thread when it is out.

**Comment by alikazai** [comment]
Hi all.
I am still having this issue after trying out all your tips. The repo i am trying to add is the Fontawesome Pro ones. this is the error i am getting..
npm ERR! code E404 npm ERR! 404 Not Found - GET https://registry.npmjs.org/@fortawesome%2fpro-light-svg-icons - Not found npm ERR! 404 npm ERR! 404 '@fortawesome/pro-light-svg-icons@5.13.0' is not in the npm registry. npm ERR! 404 You should bug the author to publish it (or use the name yourself!) npm ERR! 404 It was specified as a dependency of '__oryx_prod_node_modules' npm ERR! 404 npm ERR! 404 Note that you can also install from a npm ERR! 404 tarball, folder, http url, or git url.

i have the .npmrc file working locally and it is in the my repo i tried running the config commands again in app_build_command i also tried what @getfatday suggested yet nothing seems to be working.

any thing else i could try

**Comment by kichalla** [comment]
@alikazai Could you try the workaround that is specified below for now and see if it works:
https://github.com/microsoft/Oryx/issues/636#issuecomment-657013125

We fixed this issue at Oryx's end but are waiting on AppService and Azure Static WebApps to pick it up for their next release.

**Comment by alikazai** [comment]
@kichalla thank you for responding, i did this before it didnt work and just tried it again after your comment and this is what i get 

``
npm WARN 404 SKIPPING OPTIONAL DEPENDENCY: Not Found - GET https://registry.npmjs.org/@fortawesome%2fpro-duotone-svg-icons - Not found
``

the build continues and doesnt throw and error on this like before but then again its not really installing it. so to conclude its not working.

**Comment by kichalla** [comment]
@alikazai could you share how your package.json looks like after the change?

**Comment by alikazai** [comment]
```
{
  "name": "MyAppNamet",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@types/history": "^4.7.5",
    "@types/jest": "^25.1.2",
    "@types/js-cookie": "^2.2.5",
    "@types/node": "^13.7.1",
    "@types/react": "^16.9.43",
    "@types/react-dom": "^16.9.8",
    "@types/react-table": "^7.0.16",
    "@types/reactstrap": "^8.5.0",
    "axios": "^0.19.2",
    "bootstrap": "^4.5.0",
    "formik": "^2.1.4",
    "js-cookie": "^2.2.1",
    "node-sass": "^4.14.1",
    "react": "^16.13.1",
    "react-async": "^10.0.1",
    "react-content-loader": "^5.0.4",
    "react-dom": "^16.13.1",
    "react-intersection-observer": "^8.25.3",
    "react-router-dom": "^5.1.2",
    "react-scripts": "^3.4.1",
    "react-select": "^3.0.8",
    "react-table": "^7.0.4",
    "reactstrap": "^8.5.1",
    "typescript": "^3.9.6"
  },
  "scripts": {
    "start": "set PORT=3006 && react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject",
    "api": "json-server --watch src/api/mock-firebird-api.js --port 4000 --routes src/api/routes.json --middlewares src/api/mock-firebird-api-POSTs.js",
    "proxxy": "node src/api/proxy-helpdeskapi.js"
  },
  "eslintConfig": {
    "extends": "react-app"
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  },
  "devDependencies": {
    "@types/react-router-dom": "^5.1.3",
    "body-parser": "^1.19.0",
    "faker": "^4.1.0",
    "http-proxy-middleware": "^1.0.3",
    "json-server": "^0.16.1",
    "jsonwebtoken": "^8.5.1",
    "@fortawesome/fontawesome-pro": "^5.13.0",
    "@fortawesome/fontawesome-svg-core": "^1.2.28",
    "@fortawesome/pro-duotone-svg-icons": "^5.13.0",
    "@fortawesome/pro-light-svg-icons": "^5.13.0",
    "@fortawesome/pro-regular-svg-icons": "^5.13.0",
    "@fortawesome/pro-solid-svg-icons": "^5.13.0",
    "@fortawesome/react-fontawesome": "^0.1.9"
  }
}

```

**Comment by alikazai** [comment]
```
name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - Test
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - Test

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Build And Deploy
        env:
          CI: false
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v0.0.1-preview
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match you app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "/" # App source code path
          api_location: "" # Api source code path - optional
          app_artifact_location: "build" # Built app content directory - optional
          ###### End of Repository/Build Configurations ######

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v0.0.1-preview
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: "close"
```
