### ISSUE TITLE
Github azure action with Lerna: lerna: command not found

### ISSUE THREAD

**Issue by pkmelee337** [microsoft/Oryx#885]
### Bug Report

**At what date and time did you most recently experience the problem?**
13-12-2020 20:40UTC

**- Where did you experience the problem?**
Github actions on the action Azure/static-web-apps-deploy@v0.0.1-preview

**What happened?**
I'm trying to build my lerna repository, with an react-scripts web project and an api, but I can't get it to work. I looked for examples, but the only example I was able to find was [this one](https://github.com/microsoft/Oryx/tree/6eb32856331b221ffe4f5d0c32a175afa97a2573/tests/SampleApps/nodejs/monorepo-lerna-npm), but my repository was already looking like this in the basics. The main problem I'm struggling with is that whatever options I put at app_location and/or output_location I'm always gettings the error `/tmp/BuildScriptGenerator/45f30815be874370b2dcb47c5308aaaa/build.sh: line 223: lerna: command not found`.

I think this problem is easily reproduced by creating a simple lerna repository, but I'm not sure because I'm working from azure and github actions.

My gtihub actions is looking as followed:
```
name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
          registry-url: https://registry.npmjs.org/

      # - name: Install
      #   run: yarn install

      # - name: Build and test
      #   run: |
      #     npx lerna run build
      #     # npx lerna run test testing not yet implemented

      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v0.0.1-preview
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_WITTY_MEADOW_060764403 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match you app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "/" # App source code path
          # api_location: "api" # Api source code path - optional
          output_location: "packages/Web/build" # Built app content directory - optional
          ###### End of Repository/Build Configurations ######
        env:
          ENABLE_NODE_MONOREPO_BUILD: true

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v0.0.1-preview
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_WITTY_MEADOW_060764403 }}
          action: "close"
```

The output of a failed build is looking like this:
```
Run Azure/static-web-apps-deploy@v0.0.1-preview
  with:
    azure_static_web_apps_api_token: ***
    repo_token: ***
    action: upload
    app_location: /
    output_location: packages/Web/build
  env:
    NPM_CONFIG_USERCONFIG: /home/runner/work/_temp/.npmrc
    NODE_AUTH_TOKEN: XXXXX-XXXXX-XXXXX-XXXXX
    ENABLE_NODE_MONOREPO_BUILD: true
/usr/bin/docker run --name dff11ae5146aa9e35af70e0b108bf_4cc81f --label 179394 --workdir /github/workspace --rm -e NPM_CONFIG_USERCONFIG -e NODE_AUTH_TOKEN -e ENABLE_NODE_MONOREPO_BUILD -e INPUT_AZURE_STATIC_WEB_APPS_API_TOKEN -e INPUT_REPO_TOKEN -e INPUT_ACTION -e INPUT_APP_LOCATION -e INPUT_OUTPUT_LOCATION -e INPUT_API_BUILD_COMMAND -e INPUT_API_LOCATION -e INPUT_APP_ARTIFACT_LOCATION -e INPUT_APP_BUILD_COMMAND -e INPUT_ROUTES_LOCATION -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_RETENTION_DAYS -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e GITHUB_ACTION_REPOSITORY -e GITHUB_ACTION_REF -e GITHUB_PATH -e GITHUB_ENV -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/my-repo/my-repo":"/github/workspace" 179394:406dff11ae5146aa9e35af70e0b108bf
DeploymentId: fb8cf7db-8ca0-47f2-83d8-fb4f091edd43

App Directory Location: '/' was found.
No Api directory specified. Azure Functions will not be created.
Starting to build app with Oryx
Azure Static Web Apps utilizes Oryx to build both static applications and Azure Functions. You can find more details on Oryx here: https://github.com/microsoft/Oryx
---Oryx build logs---


Operation performed by Microsoft Oryx, https://github.com/Microsoft/Oryx
You can report issues at https://github.com/Microsoft/Oryx/issues

Oryx Version: 0.2.20201112.1, Commit: a120bb248aa8d208ca5e02d7d9d075196e79cffd, ReleaseTagName: 20201112.1

Build Operation ID: |vPLJQ2jnqlg=.db8a1eaa_
Repository Commit : 51f297ee7e22100a0281be47a24f83a9c1a78360

Detecting platforms...
Detected following platforms:
  nodejs: 14.15.1
Version '14.15.1' of platform 'nodejs' is not installed. Generating script to install it...


Source directory     : /github/workspace
Destination directory: /bin/staticsites/ss-oryx/app


Downloading and extracting 'nodejs' version '14.15.1' to '/tmp/oryx/platforms/nodejs/14.15.1'...
Downloaded in 0 sec(s).
Verifying checksum...
Extracting contents...
Done in 1 sec(s).


Using Node version:
v14.15.1

Using Yarn version:
1.22.10

Installing production dependencies in '/github/workspace/.oryx_prod_node_modules'...

Running 'yarn install --prefer-offline --production'...

yarn install v1.22.10
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
warning "lerna > @lerna/version > @lerna/github-client > @octokit/rest > @octokit/plugin-request-log@1.0.2" has unmet peer dependency "@octokit/core@>=3".
[4/4] Building fresh packages...
success Saved lockfile.
Done in 14.80s.

Copying production dependencies from '/github/workspace/.oryx_prod_node_modules' to '/github/workspace/node_modules'...
Done in 2 sec(s).

Using Lerna version:
/tmp/BuildScriptGenerator/45f30815be874370b2dcb47c5308aaaa/build.sh: line 223: lerna: command not found


---End of Oryx build logs---
Oryx has failed to build the solution.

For further information, please visit the Azure Static Web Apps documentation at https://docs.microsoft.com/en-us/azure/static-web-apps/
If you believe this behavior is unexpected, please raise a GitHub issue at https://github.com/azure/static-web-apps/issues/
Exiting
```

**Comment by qianz2** [comment]
Hi @pkmelee337, I believe that either the build image was not updated or lerna tool was not included in the build image of Azure/static-web-apps-deploy, I'll investigate into it, thanks for reporting.

**Comment by pkmelee337** [comment]
Thank you! Is there a temporary workaround available you think? No problem if not, then I'll just wait. :-)

**Comment by qianz2** [comment]
Hi @pkmelee337, you can try using PRE_BUILD_COMMAND="npm install -g lerna" to install lerna tool before building the app. If it's not working, you'll probably need to wait the fix.

**Comment by pkmelee337** [comment]
Thanks, didn't get it to work, so I'll wait for the fix. 👍

**Comment by qianz2** [comment]
Hi @pkmelee337 , please try this workaround instead, it worked for us, the key point is that oryx already dynamically installed node 14.15.1 but the path was not updated so we need to update it from pre build command as well: 

export PRE_BUILD_COMMAND="PATH=\"/tmp/oryx/platforms/nodejs/14.15.1/bin:$PATH\" && npm install -g lerna"

**Comment by pkmelee337** [comment]
Hi @qianz2! Thanks for your help. The app build is succeeding now, but the api build is still failing. From the logs I can see the API build is done with npm (`npm install --unsafe-perm --production`). I'm using a local library repository (with lerna/yarn submodules) so it needs a yarn install because npm is not able to find this library. This is how my build action is looking right now:

```
- name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v0.0.1-preview
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_WITTY_MEADOW_060764403 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match you app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "/" # App source code path
          api_location: "packages/API" # Api source code path - optional
          output_location: "packages/Web/build" # Built app content directory - optional
          app_build_command: 'PATH="/tmp/oryx/platforms/nodejs/14.15.1/bin:$PATH" && yarn global add lerna && lerna run build'
          api_build_command: 'PATH="/tmp/oryx/platforms/nodejs/14.15.1/bin:$PATH" && yarn global add lerna && lerna run build'
          ###### End of Repository/Build Configurations ######
        env:
          ENABLE_NODE_MONOREPO_BUILD: true
```

So I added the build command for the api too, but it does not seem to be respected. I'm seeing this install on the app also, but this is done with yarn: `Running 'yarn install --prefer-offline --production'...`

**Comment by qianz2** [comment]
Hi @pkmelee337, could you make sure your `lerna.json` file has   `"npmClient": "yarn",` in it because Oryx will detect this line and to decide if it will run npm package install command or yarn package install command.

**Comment by qianz2** [comment]
Also make sure you have a` yarn.lock` file in the repo as well

**Comment by pkmelee337** [comment]
Yes, my lerna.json has this line and I also have a yarn.lock file in the repo. The application build is using yarn, so I don;t think this is the problem. The api build however is done in another folder. (which doesn't make sense, because it is already build with lerna on the application build) When I add an empty yarn.lock file to the api folder it is using yarn to build, but still fails on the library dependendy.

**Comment by arroyc** [comment]
@pkmelee337  would you be able to share the latest log on what you are getting now .. sorry for your trouble ... we will try to repro and find a fix to this

**Comment by pkmelee337** [comment]
No problem! Just tried again and here are the logs. Building of my web folder works fine, but API is still failing. Currently it is using npm, but tried an empty .yarn file in my api folder, and with yarn install I get the same error message.

```
Using Node version:
v14.15.1

Using Npm version:
6.14.8

Installing production dependencies in '/github/workspace/packages/API/.oryx_prod_node_modules'...

Running 'npm install --unsafe-perm --production'...

npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated mkdirp-promise@5.0.1: This package is broken and no longer maintained. 'mkdirp' itself supports promises now, please switch to that.
npm WARN deprecated multicodec@0.5.7: stable api reached
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@<myprojectname>%2flibrary - Not found
npm ERR! 404 
npm ERR! 404  '@<myprojectname>/library@^1.0.0' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of '.oryx_prod_node_modules'
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     /github/home/.npm/_logs/2021-01-13T14_17_41_599Z-debug.log


---End of Oryx build logs---
Oryx has failed to build the solution.

For further information, please visit the Azure Static Web Apps documentation at https://docs.microsoft.com/en-us/azure/static-web-apps/
If you believe this behavior is unexpected, please raise a GitHub issue at https://github.com/azure/static-web-apps/issues/
Exiting
```

My build step is looking as followed:
```
- name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v0.0.1-preview
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_WITTY_MEADOW_060764403 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match you app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "/" # App source code path
          api_location: "/packages/API" # Api source code path - optional
          output_location: "packages/Web/build" # Built app content directory - optional
          app_build_command: 'PATH="/tmp/oryx/platforms/nodejs/14.15.1/bin:$PATH" && yarn global add lerna && lerna run build'
          api_build_command: 'PATH="/tmp/oryx/platforms/nodejs/14.15.1/bin:$PATH" && yarn global add lerna && lerna run build'
          ###### End of Repository/Build Configurations ######
        env:
          ENABLE_NODE_MONOREPO_BUILD: true
```

**Comment by william-msft** [comment]
Hi @pkmelee337, hope all is well, if this issue needs further investigation please feel free to reach out to me. I'd be more than happy to help. I reached out via email before just in case. Stay safe!

**Comment by william-msft** [comment]
Moving context from email over to this thread:
`Basically, I have a Lerna monorepo with 3 packages: Web, API, and library. I want to publish the Web and API folder to the same static web app. Doing this I'm having the following problems:
1. I have to add an app_build_command to support the Lerna build (otherwise I'm getting an error message that Lerna cannot be found) The app_build_command is as followed:

app_build_command: 'PATH="/tmp/oryx/platforms/nodejs/14.17.3/bin:$PATH" && yarn global add lerna && lerna run build'

2. When I add the above command the Lerna build is working, but after that, the API build breaks with an npm not found error. The problem is that it cannot find the library package, which is logical because this package isn't an NPM repository and can only be found by using Lerna/yarn workspaces. So the first problem is that the API build uses NPM instead of Yarn. The second problem is that the web build I'm using is already building the whole solution. Therefore the api shouldn't trigger a build again and can just get published.

My build and deploy job is currently looking as followed:

build_and_deploy_job:

    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')

    runs-on: ubuntu-latest

    name: Build and Deploy Job

    steps:

      - uses: actions/checkout@v2

        with:

          submodules: true

      - uses: actions/setup-node@v2

        with:

          node-version: 14

          cache: 'yarn'




      # - name: Install

      #   run: yarn install




      # - name: Build and test

      #   run: |

      #     npx lerna run build

      #     # npx lerna run test testing not yet implemented




      - name: Build And Deploy

        id: builddeploy

        uses: Azure/static-web-apps-deploy@v1

        with:

          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_WITTY_MEADOW_060764403 }}

          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)

          action: "upload"

          ###### Repository/Build Configurations - These values can be configured to match you app requirements. ######

          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig

          app_location: "/" # App source code path

          api_location: "/packages/API" # Api source code path - optional

          output_location: "packages/Web/build" # Built app content directory - optional

          app_build_command: 'PATH="/tmp/oryx/platforms/nodejs/14.17.3/bin:$PATH" && yarn global add lerna && lerna run build'

          api_build_command: ''

          ###### End of Repository/Build Configurations ######

        env:

          ENABLE_NODE_MONOREPO_BUILD: true`

**Comment by anthonychu** [comment]
As it sounds like you need to build both your frontend and the API with Lerna, your best bet is to run the Lerna build separately in a separate step prior to the `Azure/static-web-apps-deploy` action and only use the action to deploy the build output.

This is what the workflow might look like:

```yaml
- name: Build
  run: | # run all the necessary commands to build your app and API
    npx lerna run build 
- name: Deploy
    id: builddeploy
    uses: Azure/static-web-apps-deploy@v1
    with:
      azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_WITTY_MEADOW_060764403 }}
      repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
      action: "upload"
      ###### Repository/Build Configurations - These values can be configured to match you app requirements. ######
      # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
      app_location: "" # path to app build output
      api_location: "" # path to api build output
      skip_app_build: true
      ###### End of Repository/Build Configurations ######
```

We don't have a skip api build option yet, so the Static Web Apps action will still try to run a build in the api location you provided. I'm not sure if you can get around this. But if you run into issues, let us know what you're running into and we might be able to provide a workaround.
