### ISSUE TITLE
When running StaticSitesClient inside an Azure Pipeline task, I get error "Oops... An unexpected error has occurred."

### ISSUE THREAD

**Issue by StefH** [microsoft/Oryx#938]
### Bug Report

When running this task in an Azure pipeline (Linux Ubuntu 18.04):
``` yaml
- task: CmdLine@2
  target: staticappsclient
  inputs:
    script: |
      cd /bin/staticsites/
      ./StaticSitesClient upload --verbose True --apiToken $(API_TOKEN) --workdir $(Build.SourcesDirectory) --api Api --app Client --outputLocation wwwroot
```

I get this logging:
```
DeploymentId: 473e8ebd-c61e-4eb6-8df8-b006872149ab

Verbose logging enabled
Build timeout not specified, defaulting to 15 minutes
App Directory Location: 'Client' was found.
Api Directory Location: 'Api' was found.
Starting to build app with Oryx
Azure Static Web Apps utilizes Oryx to build both static applications and Azure Functions. You can find more details on Oryx here: https://github.com/microsoft/Oryx
---Oryx build logs---


Operation performed by Microsoft Oryx, https://github.com/Microsoft/Oryx
You can report issues at https://github.com/Microsoft/Oryx/issues

Oryx Version: 0.2.20201112.1, Commit: a120bb248aa8d208ca5e02d7d9d075196e79cffd, ReleaseTagName: 20201112.1

Build Operation ID: |6nwoJyOp4jE=.bce0b52d_
Repository Commit : 82659d6e0adfe29c75c83d48171d1b485a02d34a

Detecting platforms...
Detected following platforms:
  dotnet: 3.1.10
Version '3.1.10' of platform 'dotnet' is not installed. Generating script to install it...
Error: Oops... An unexpected error has occurred.


---End of Oryx build logs---
Oryx build has completed. Took 3.3117778 seconds. Exit Code: 1
Oryx has failed to build the solution.
```

The error occurs at:
```
Version '3.1.10' of platform 'dotnet' is not installed. Generating script to install it...
Error: Oops... An unexpected error has occurred.
```

What could be the cause ? And how to add more debug logging when running the StaticSitesClient?
