### ISSUE TITLE
When running StaticSitesClient inside an Azure Pipeline task, I get error "Oops... An unexpected error has occurred." - part 2

### ISSUE THREAD

**Issue by StefH** [microsoft/Oryx#945]
Followup from https://github.com/microsoft/Oryx/issues/938

Using the latest docker image : `mcr.microsoft.com/appsvc/staticappsclient`

When running the **StaticSitesClient** as a CmdLine@2 or as Bash@3
``` yaml
- task: Bash@3
  target: staticappsclient
  inputs:
    targetType: inline
    script: |
      cd /bin/staticsites/
      ./StaticSitesClient upload --verbose True --apiToken $(API_TOKEN) --workdir $(Build.SourcesDirectory) --api Api --app Client --outputLocation wwwroot
```

I still get errors like:
```
Detecting platforms...
Detected following platforms:
  dotnet: 3.1.12
Version '3.1.12' of platform 'dotnet' is not installed. Generating script to install it...
Error: Oops... An unexpected error has occurred.
```

Full log can be found here:
https://dev.azure.com/stef/71c3694d-5a43-4010-b00f-865c726f6322/_apis/build/builds/4731/logs/7

And my work-in-progress yaml pipeline can be found here:
https://github.com/StefH/BlazorAzureStaticWebAppViaAzurePipelines/blob/azure-pipelines-container/azure-pipelines.yml
