### ISSUE TITLE
Angular (Node) build fails - ngcc: not found

### ISSUE THREAD

**Issue by dennisameling** [microsoft/Oryx#959]
Cross-ref to issue in `Azure/static-web-apps`: https://github.com/Azure/static-web-apps/issues/231

### Bug Report

- At what date and time did you most recently experience the problem?

March 17 2021, 13:30 CEST

- Where did you experience the problem? E.g. Azure Web Apps, Azure Functions, Azure Container Registry, or offline use.

Azure Static Web Apps (GitHub Actions: [Azure/static-web-apps-deploy@v0.0.1-preview](https://github.com/marketplace/actions/azure-static-web-apps-deploy))

- If your repo is publicly available please share its URL:

Nope, sorry, but could create a minimal repo that shows the problem

- What happened?

1. Followed the [Azure Static Web Apps Quick Start](https://docs.microsoft.com/nl-nl/azure/static-web-apps/get-started-portal)
2. This created a GitHub Action in our repo **for our existing Angular application** with the following config:

```YAML
jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v0.0.1-preview
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_YELLOW_STONE_06306FC03 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "/" # App source code path
          api_location: "/api" # Api source code path - optional
          output_location: "www" # Built app content directory - optional
          ###### End of Repository/Build Configurations ######
```

3. The GitHub Actions workflow ran and errored with `ngcc: not found`.

- What did you expect or want to happen?

The GitHub Actions workflow should build the Angular app without erroring.

- How can we reproduce it?

The problem is happening because Oryx only installs production dependencies only (`npm install --unsafe-perm --production`), also see https://github.com/Azure/static-web-apps/issues/231. We were able to work around it by removing a `postinstall` command in `package.json` and adding the following to the GitHub Actions config:

```YAML
env:
  CUSTOM_BUILD_COMMAND: 'npm ci && npm run build' 
```

See https://github.com/Azure/static-web-apps/issues/231#issuecomment-801067998 for details.

There's not currently an Oryx configuration options available to customize the NPM install command (we need `npm ci` in our case). Could you either, by default, include dev dependencies in the installation step, or create a configuration options that we can use to customize the NPM install command? Something like `CUSTOM_INSTALL_COMMAND` probably?

- Do you have log output? Please include between the backticks:

```
Starting to build app with Oryx
Azure Static Web Apps utilizes Oryx to build both static applications and Azure Functions. You can find more details on Oryx here: https://github.com/microsoft/Oryx
---Oryx build logs---


Operation performed by Microsoft Oryx, https://github.com/Microsoft/Oryx
You can report issues at https://github.com/Microsoft/Oryx/issues

Oryx Version: 0.2.20210225.1, Commit: ac3044e35d3dc78dce05ba4d552bbe144029a673, ReleaseTagName: 20210225.1

Build Operation ID: |CkBmLNdCBx8=.32c30caa_
Repository Commit : fa42b2a407f0621cca89f900680af9cbc88ba0e7

Detecting platforms...
Detected following platforms:
  nodejs: 14.15.1
  java: 11.0.8
Version '14.15.1' of platform 'nodejs' is not installed. Generating script to install it...
Version '11.0.8' of platform 'java' is not installed. Generating script to install it...


Source directory     : /github/workspace
Destination directory: /bin/staticsites/ss-oryx/app


Downloading and extracting 'nodejs' version '14.15.1' to '/tmp/oryx/platforms/nodejs/14.15.1'...
Downloaded in 0 sec(s).
Verifying checksum...
Extracting contents...
Done in 2 sec(s).


Downloading and extracting 'java' version '11.0.8' to '/tmp/oryx/platforms/java/11.0.8'...
Downloaded in 1 sec(s).
Verifying checksum...
Extracting contents...
Done in 5 sec(s).


Downloading and extracting 'maven' version '3.6.3' to '/tmp/oryx/platforms/maven/3.6.3'...
Downloaded in 1 sec(s).
Verifying checksum...
Extracting contents...
Done in 1 sec(s).


Using Node version:
v14.15.1

Using Npm version:
6.14.8

Installing production dependencies in '/github/workspace/.oryx_prod_node_modules'...

Running 'npm install --unsafe-perm --production'...


> REDACTED@1.0.0 postinstall /github/workspace/.oryx_prod_node_modules
> ngcc

sh: 1: ngcc: not found
npm ERR! code ELIFECYCLE
npm ERR! syscall spawn
npm ERR! file sh
npm ERR! errno ENOENT
npm ERR! REDACTED@1.0.0 postinstall: `ngcc`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the REDACTED@1.0.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /github/home/.npm/_logs/2021-03-17T11_47_27_382Z-debug.log


---End of Oryx build logs---
Oryx has failed to build the solution.

For further information, please visit the Azure Static Web Apps documentation at https://docs.microsoft.com/en-us/azure/static-web-apps/
If you believe this behavior is unexpected, please raise a GitHub issue at https://github.com/azure/static-web-apps/issues/
Exiting
```
